export const LARGE_DISPLAY_LENGTH = 12;
export const LARGE_DISPLAY_ADDITIONAL_LENGTH = 3;

export const MEDIUM_DISPLAY_LENGTH = 8;
export const MEDIUM_DISPLAY_ADDITIONAL_LENGTH = 2;

export const SMALL_DISPLAY_LENGTH = 5;
export const SMALL_DISPLAY_ADDITIONAL_LENGTH = 1;
